
project_id = "sqrlsxmwvmgmbmcyaxcq"

[auth]
# Completely disable email confirmations for immediate signup
enable_signup = true
enable_confirmations = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
# Completely disable rate limiting
max_frequency = "never"
secure_email_change_enabled = false

# Do not include any SMTP configuration to prevent email sending

[auth.email.template.invite]
action_url = "{{ .ConfirmationURL }}"

[auth.email.template.confirmation]
action_url = "{{ .ConfirmationURL }}"

[auth.email.template.recovery]
action_url = "{{ .ConfirmationURL }}"

[functions.send-email]
verify_jwt = false
