
project_id = "sqrlsxmwvmgmbmcyaxcq"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.email.template.invite]
action_url = "{{ .ConfirmationURL }}"

[functions.send-email]
verify_jwt = false
