
project_id = "sqrlsxmwvmgmbmcyaxcq"

[auth]
# Disable email confirmations completely for immediate signup
enable_signup = true
enable_confirmations = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
# Completely remove rate limiting for development
# Setting to 0 disables rate limiting entirely
max_frequency = "0s"

# Remove SMTP configuration to avoid conflicts
# [auth.email.smtp]

[auth.email.template.invite]
action_url = "{{ .ConfirmationURL }}"

[auth.email.template.confirmation]
action_url = "{{ .ConfirmationURL }}"

[auth.email.template.recovery]
action_url = "{{ .ConfirmationURL }}"

[functions.send-email]
verify_jwt = false
