// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqrlsxmwvmgmbmcyaxcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxcmxzeG13dm1nbWJtY3lheGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTcyMTAsImV4cCI6MjA2MDAzMzIxMH0.xZQ0SGg82QG_TdYtxQU7ccy0mvb_3HvyQj8xbT8FUYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);